// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseFolder() {
  return window['go']['main']['App']['BrowseFolder']();
}

export function CancelExport() {
  return window['go']['main']['App']['CancelExport']();
}

export function ExportAllNotebooks(arg1, arg2) {
  return window['go']['main']['App']['ExportAllNotebooks'](arg1, arg2);
}

export function ExportBackup(arg1) {
  return window['go']['main']['App']['ExportBackup'](arg1);
}

export function ExportNotebook(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportNotebook'](arg1, arg2, arg3);
}

export function FormatSize(arg1) {
  return window['go']['main']['App']['FormatSize'](arg1);
}

export function GetBackupContents() {
  return window['go']['main']['App']['GetBackupContents']();
}

export function GetBackupSize() {
  return window['go']['main']['App']['GetBackupSize']();
}

export function GetDefaultDownloadsPath() {
  return window['go']['main']['App']['GetDefaultDownloadsPath']();
}

export function GetNotebooks() {
  return window['go']['main']['App']['GetNotebooks']();
}

export function GetOneNoteBackupPath() {
  return window['go']['main']['App']['GetOneNoteBackupPath']();
}

export function GetOneNoteVersion() {
  return window['go']['main']['App']['GetOneNoteVersion']();
}
